package com.redline.anistalker.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFB871)
val md_theme_dark_onPrimary = Color(0xFF4A2800)
val md_theme_dark_primaryContainer = Color(0xFF6A3C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCBE)
val md_theme_dark_secondary = Color(0xFFE1C1A4)
val md_theme_dark_onSecondary = Color(0xFF402C18)
val md_theme_dark_secondaryContainer = Color(0xFF59422C)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCBE)
val md_theme_dark_tertiary = Color(0xFFC0CC9A)
val md_theme_dark_onTertiary = Color(0xFF2B3410)
val md_theme_dark_tertiaryContainer = Color(0xFF414B24)
val md_theme_dark_onTertiaryContainer = Color(0xFFDCE8B4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF9D8E81)
val md_theme_dark_background = Color(0xFF1E1E1E)
val md_theme_dark_onBackground = Color(0xFFEBE0D9)
val md_theme_dark_surface = Color(0xFF17120F)
val md_theme_dark_onSurface = Color(0xFFCFC5BE)
val md_theme_dark_surfaceVariant = Color(0xFF51453A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C3B5)
val md_theme_dark_inverseSurface = Color(0xFFEBE0D9)
val md_theme_dark_inverseOnSurface = Color(0xFF201B16)
val md_theme_dark_inversePrimary = Color(0xFF8B5000)
val md_theme_dark_surfaceTint = Color(0xFFFFB871)
val md_theme_dark_outlineVariant = Color(0xFF51453A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFF8B675)

val secondary_background = Color(0xFF2C2C2C)
val dullRed = Color(0xFFC51515)
val dark_background = Color(0xFF0E0E0E)
val mid_background = Color(0xFF3C3C3C)